//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.19 at 01:01:12 PM BST 
//


package EngineBookShare;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="messages" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="book">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="metadata">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="available-to-download" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="bookshare-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="brief-synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="complete-synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="content-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                             &lt;element name="dtbook-size" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *                             &lt;element name="freely-available" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="images" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                             &lt;element name="isbn13" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="publish-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "messages",
    "book"
})
@XmlRootElement(name = "bookshare")
public class Bookshare {

    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected Object messages;
    @XmlElement(required = true)
    protected Bookshare.Book book;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMessages(Object value) {
        this.messages = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * @return
     *     possible object is
     *     {@link Bookshare.Book }
     *     
     */
    public Bookshare.Book getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bookshare.Book }
     *     
     */
    public void setBook(Bookshare.Book value) {
        this.book = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="metadata">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="available-to-download" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="bookshare-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="brief-synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="complete-synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="content-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *                   &lt;element name="dtbook-size" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
     *                   &lt;element name="freely-available" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="images" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                   &lt;element name="isbn13" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="publish-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "metadata"
    })
    public static class Book {

        @XmlElement(required = true)
        protected Bookshare.Book.Metadata metadata;

        /**
         * Gets the value of the metadata property.
         * 
         * @return
         *     possible object is
         *     {@link Bookshare.Book.Metadata }
         *     
         */
        public Bookshare.Book.Metadata getMetadata() {
            return metadata;
        }

        /**
         * Sets the value of the metadata property.
         * 
         * @param value
         *     allowed object is
         *     {@link Bookshare.Book.Metadata }
         *     
         */
        public void setMetadata(Bookshare.Book.Metadata value) {
            this.metadata = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="available-to-download" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="bookshare-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="brief-synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="complete-synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="content-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="copyright" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
         *         &lt;element name="dtbook-size" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
         *         &lt;element name="freely-available" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="images" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *         &lt;element name="isbn13" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="publish-date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="quality" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "author",
            "availableToDownload",
            "bookshareId",
            "briefSynopsis",
            "completeSynopsis",
            "contentId",
            "copyright",
            "dtbookSize",
            "freelyAvailable",
            "images",
            "isbn13",
            "language",
            "publishDate",
            "publisher",
            "quality",
            "title",
            "category"
        })
        public static class Metadata {

            @XmlElement(required = true)
            protected List<String> author;
            @XmlElement(name = "available-to-download")
            @XmlSchemaType(name = "unsignedByte")
            protected short availableToDownload;
            @XmlElement(name = "bookshare-id")
            @XmlSchemaType(name = "unsignedInt")
            protected long bookshareId;
            @XmlElement(name = "brief-synopsis", required = true)
            protected String briefSynopsis;
            @XmlElement(name = "complete-synopsis", required = true)
            protected String completeSynopsis;
            @XmlElement(name = "content-id")
            @XmlSchemaType(name = "unsignedInt")
            protected long contentId;
            @XmlSchemaType(name = "unsignedShort")
            protected int copyright;
            @XmlElement(name = "dtbook-size")
            @XmlSchemaType(name = "unsignedInt")
            protected long dtbookSize;
            @XmlElement(name = "freely-available")
            @XmlSchemaType(name = "unsignedByte")
            protected short freelyAvailable;
            @XmlSchemaType(name = "unsignedByte")
            protected short images;
            @XmlElement(required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger isbn13;
            @XmlElement(required = true)
            protected String language;
            @XmlElement(name = "publish-date", required = true)
            protected String publishDate;
            @XmlElement(required = true)
            protected String publisher;
            @XmlElement(required = true)
            protected String quality;
            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected List<String> category;

            /**
             * Gets the value of the author property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the author property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuthor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAuthor() {
                if (author == null) {
                    author = new ArrayList<String>();
                }
                return this.author;
            }

            /**
             * Gets the value of the availableToDownload property.
             * 
             */
            public short getAvailableToDownload() {
                return availableToDownload;
            }

            /**
             * Sets the value of the availableToDownload property.
             * 
             */
            public void setAvailableToDownload(short value) {
                this.availableToDownload = value;
            }

            /**
             * Gets the value of the bookshareId property.
             * 
             */
            public long getBookshareId() {
                return bookshareId;
            }

            /**
             * Sets the value of the bookshareId property.
             * 
             */
            public void setBookshareId(long value) {
                this.bookshareId = value;
            }

            /**
             * Gets the value of the briefSynopsis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBriefSynopsis() {
                return briefSynopsis;
            }

            /**
             * Sets the value of the briefSynopsis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBriefSynopsis(String value) {
                this.briefSynopsis = value;
            }

            /**
             * Gets the value of the completeSynopsis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCompleteSynopsis() {
                return completeSynopsis;
            }

            /**
             * Sets the value of the completeSynopsis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCompleteSynopsis(String value) {
                this.completeSynopsis = value;
            }

            /**
             * Gets the value of the contentId property.
             * 
             */
            public long getContentId() {
                return contentId;
            }

            /**
             * Sets the value of the contentId property.
             * 
             */
            public void setContentId(long value) {
                this.contentId = value;
            }

            /**
             * Gets the value of the copyright property.
             * 
             */
            public int getCopyright() {
                return copyright;
            }

            /**
             * Sets the value of the copyright property.
             * 
             */
            public void setCopyright(int value) {
                this.copyright = value;
            }

            /**
             * Gets the value of the dtbookSize property.
             * 
             */
            public long getDtbookSize() {
                return dtbookSize;
            }

            /**
             * Sets the value of the dtbookSize property.
             * 
             */
            public void setDtbookSize(long value) {
                this.dtbookSize = value;
            }

            /**
             * Gets the value of the freelyAvailable property.
             * 
             */
            public short getFreelyAvailable() {
                return freelyAvailable;
            }

            /**
             * Sets the value of the freelyAvailable property.
             * 
             */
            public void setFreelyAvailable(short value) {
                this.freelyAvailable = value;
            }

            /**
             * Gets the value of the images property.
             * 
             */
            public short getImages() {
                return images;
            }

            /**
             * Sets the value of the images property.
             * 
             */
            public void setImages(short value) {
                this.images = value;
            }

            /**
             * Gets the value of the isbn13 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getIsbn13() {
                return isbn13;
            }

            /**
             * Sets the value of the isbn13 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setIsbn13(BigInteger value) {
                this.isbn13 = value;
            }

            /**
             * Gets the value of the language property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLanguage() {
                return language;
            }

            /**
             * Sets the value of the language property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLanguage(String value) {
                this.language = value;
            }

            /**
             * Gets the value of the publishDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublishDate() {
                return publishDate;
            }

            /**
             * Sets the value of the publishDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublishDate(String value) {
                this.publishDate = value;
            }

            /**
             * Gets the value of the publisher property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPublisher() {
                return publisher;
            }

            /**
             * Sets the value of the publisher property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPublisher(String value) {
                this.publisher = value;
            }

            /**
             * Gets the value of the quality property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuality() {
                return quality;
            }

            /**
             * Sets the value of the quality property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuality(String value) {
                this.quality = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the category property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the category property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCategory().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCategory() {
                if (category == null) {
                    category = new ArrayList<String>();
                }
                return this.category;
            }

        }

    }

}
