//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.14 at 05:54:58 PM BST 
//


package EngineLibraryThing;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the librarythingXml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: librarythingXml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList createLtmlItemCommonknowledgeFieldList() {
        return new Ltml.Item.Commonknowledge.FieldList();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.Date }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.Date createLtmlItemCommonknowledgeFieldListFieldVersionListVersionDate() {
        return new Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.Date();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.FactList }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.FactList createLtmlItemCommonknowledgeFieldListFieldVersionListVersionFactList() {
        return new Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.FactList();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version createLtmlItemCommonknowledgeFieldListFieldVersionListVersion() {
        return new Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList.Field }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList.Field createLtmlItemCommonknowledgeFieldListField() {
        return new Ltml.Item.Commonknowledge.FieldList.Field();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.Person }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.Person createLtmlItemCommonknowledgeFieldListFieldVersionListVersionPerson() {
        return new Ltml.Item.Commonknowledge.FieldList.Field.VersionList.Version.Person();
    }

    /**
     * Create an instance of {@link Response.Err }
     * 
     */
    public Response.Err createResponseErr() {
        return new Response.Err();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge }
     * 
     */
    public Ltml.Item.Commonknowledge createLtmlItemCommonknowledge() {
        return new Ltml.Item.Commonknowledge();
    }

    /**
     * Create an instance of {@link Ltml }
     * 
     */
    public Ltml createLtml() {
        return new Ltml();
    }

    /**
     * Create an instance of {@link Ltml.Item.Commonknowledge.FieldList.Field.VersionList }
     * 
     */
    public Ltml.Item.Commonknowledge.FieldList.Field.VersionList createLtmlItemCommonknowledgeFieldListFieldVersionList() {
        return new Ltml.Item.Commonknowledge.FieldList.Field.VersionList();
    }

    /**
     * Create an instance of {@link Ltml.Item.Author }
     * 
     */
    public Ltml.Item.Author createLtmlItemAuthor() {
        return new Ltml.Item.Author();
    }

    /**
     * Create an instance of {@link Ltml.Item }
     * 
     */
    public Ltml.Item createLtmlItem() {
        return new Ltml.Item();
    }

}
