//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.07 at 11:06:56 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.librarything.com/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package EngineLibraryThing;
