//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.14 at 04:37:23 PM BST 
//


package EngineIsbnDb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BookList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BookData">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TitleLong" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AuthorsText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PublisherText">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="publisher_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Details">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="change_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                     &lt;attribute name="price_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                     &lt;attribute name="edition_info" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="physical_description_text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="lcc_number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="dewey_decimal_normalized" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="dewey_decimal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Authors">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Person" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="book_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="isbn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="isbn13" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="total_results" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="page_size" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="page_number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="shown_results" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="server_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorMessage",
    "bookList"
})
@XmlRootElement(name = "ISBNdb")
public class ISBNdb {

    @XmlElement(name = "ErrorMessage", required = true)
    protected String errorMessage;
    @XmlElement(name = "BookList", required = true)
    protected ISBNdb.BookList bookList;
    @XmlAttribute(name = "server_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar serverTime;

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the bookList property.
     * 
     * @return
     *     possible object is
     *     {@link ISBNdb.BookList }
     *     
     */
    public ISBNdb.BookList getBookList() {
        return bookList;
    }

    /**
     * Sets the value of the bookList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISBNdb.BookList }
     *     
     */
    public void setBookList(ISBNdb.BookList value) {
        this.bookList = value;
    }

    /**
     * Gets the value of the serverTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getServerTime() {
        return serverTime;
    }

    /**
     * Sets the value of the serverTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setServerTime(XMLGregorianCalendar value) {
        this.serverTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BookData">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TitleLong" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AuthorsText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PublisherText">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="publisher_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Details">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="change_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                           &lt;attribute name="price_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                           &lt;attribute name="edition_info" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="physical_description_text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="lcc_number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="dewey_decimal_normalized" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="dewey_decimal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Authors">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Person" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="book_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="isbn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="isbn13" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="total_results" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="page_size" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="page_number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="shown_results" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bookData"
    })
    public static class BookList {

        @XmlElement(name = "BookData", required = true)
        protected ISBNdb.BookList.BookData bookData;
        @XmlAttribute(name = "total_results", required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short totalResults;
        @XmlAttribute(name = "page_size", required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short pageSize;
        @XmlAttribute(name = "page_number", required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short pageNumber;
        @XmlAttribute(name = "shown_results", required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short shownResults;

        /**
         * Gets the value of the bookData property.
         * 
         * @return
         *     possible object is
         *     {@link ISBNdb.BookList.BookData }
         *     
         */
        public ISBNdb.BookList.BookData getBookData() {
            return bookData;
        }

        /**
         * Sets the value of the bookData property.
         * 
         * @param value
         *     allowed object is
         *     {@link ISBNdb.BookList.BookData }
         *     
         */
        public void setBookData(ISBNdb.BookList.BookData value) {
            this.bookData = value;
        }

        /**
         * Gets the value of the totalResults property.
         * 
         */
        public short getTotalResults() {
            return totalResults;
        }

        /**
         * Sets the value of the totalResults property.
         * 
         */
        public void setTotalResults(short value) {
            this.totalResults = value;
        }

        /**
         * Gets the value of the pageSize property.
         * 
         */
        public short getPageSize() {
            return pageSize;
        }

        /**
         * Sets the value of the pageSize property.
         * 
         */
        public void setPageSize(short value) {
            this.pageSize = value;
        }

        /**
         * Gets the value of the pageNumber property.
         * 
         */
        public short getPageNumber() {
            return pageNumber;
        }

        /**
         * Sets the value of the pageNumber property.
         * 
         */
        public void setPageNumber(short value) {
            this.pageNumber = value;
        }

        /**
         * Gets the value of the shownResults property.
         * 
         */
        public short getShownResults() {
            return shownResults;
        }

        /**
         * Sets the value of the shownResults property.
         * 
         */
        public void setShownResults(short value) {
            this.shownResults = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TitleLong" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AuthorsText" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PublisherText">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="publisher_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Details">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="change_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                 &lt;attribute name="price_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                 &lt;attribute name="edition_info" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="physical_description_text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="lcc_number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="dewey_decimal_normalized" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="dewey_decimal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Summary" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Authors">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Person" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="book_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="isbn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="isbn13" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "titleLong",
            "authorsText",
            "publisherText",
            "details",
            "summary",
            "notes",
            "authors"
        })
        public static class BookData {

            @XmlElement(name = "Title", required = true)
            protected String title;
            @XmlElement(name = "TitleLong", required = true)
            protected String titleLong;
            @XmlElement(name = "AuthorsText", required = true)
            protected String authorsText;
            @XmlElement(name = "PublisherText", required = true)
            protected ISBNdb.BookList.BookData.PublisherText publisherText;
            @XmlElement(name = "Details", required = true)
            protected ISBNdb.BookList.BookData.Details details;
            @XmlElement(name = "Summary", required = true)
            protected String summary;
            @XmlElement(name = "Notes", required = true)
            protected String notes;
            @XmlElement(name = "Authors", required = true)
            protected ISBNdb.BookList.BookData.Authors authors;
            @XmlAttribute(name = "book_id", required = true)
            protected String bookId;
            @XmlAttribute(required = true)
            protected String isbn;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger isbn13;

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the titleLong property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitleLong() {
                return titleLong;
            }

            /**
             * Sets the value of the titleLong property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitleLong(String value) {
                this.titleLong = value;
            }

            /**
             * Gets the value of the authorsText property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuthorsText() {
                return authorsText;
            }

            /**
             * Sets the value of the authorsText property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuthorsText(String value) {
                this.authorsText = value;
            }

            /**
             * Gets the value of the publisherText property.
             * 
             * @return
             *     possible object is
             *     {@link ISBNdb.BookList.BookData.PublisherText }
             *     
             */
            public ISBNdb.BookList.BookData.PublisherText getPublisherText() {
                return publisherText;
            }

            /**
             * Sets the value of the publisherText property.
             * 
             * @param value
             *     allowed object is
             *     {@link ISBNdb.BookList.BookData.PublisherText }
             *     
             */
            public void setPublisherText(ISBNdb.BookList.BookData.PublisherText value) {
                this.publisherText = value;
            }

            /**
             * Gets the value of the details property.
             * 
             * @return
             *     possible object is
             *     {@link ISBNdb.BookList.BookData.Details }
             *     
             */
            public ISBNdb.BookList.BookData.Details getDetails() {
                return details;
            }

            /**
             * Sets the value of the details property.
             * 
             * @param value
             *     allowed object is
             *     {@link ISBNdb.BookList.BookData.Details }
             *     
             */
            public void setDetails(ISBNdb.BookList.BookData.Details value) {
                this.details = value;
            }

            /**
             * Gets the value of the summary property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSummary() {
                return summary;
            }

            /**
             * Sets the value of the summary property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSummary(String value) {
                this.summary = value;
            }

            /**
             * Gets the value of the notes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNotes() {
                return notes;
            }

            /**
             * Sets the value of the notes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNotes(String value) {
                this.notes = value;
            }

            /**
             * Gets the value of the authors property.
             * 
             * @return
             *     possible object is
             *     {@link ISBNdb.BookList.BookData.Authors }
             *     
             */
            public ISBNdb.BookList.BookData.Authors getAuthors() {
                return authors;
            }

            /**
             * Sets the value of the authors property.
             * 
             * @param value
             *     allowed object is
             *     {@link ISBNdb.BookList.BookData.Authors }
             *     
             */
            public void setAuthors(ISBNdb.BookList.BookData.Authors value) {
                this.authors = value;
            }

            /**
             * Gets the value of the bookId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBookId() {
                return bookId;
            }

            /**
             * Sets the value of the bookId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBookId(String value) {
                this.bookId = value;
            }

            /**
             * Gets the value of the isbn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsbn() {
                return isbn;
            }

            /**
             * Sets the value of the isbn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsbn(String value) {
                this.isbn = value;
            }

            /**
             * Gets the value of the isbn13 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getIsbn13() {
                return isbn13;
            }

            /**
             * Sets the value of the isbn13 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setIsbn13(BigInteger value) {
                this.isbn13 = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Person" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "person"
            })
            public static class Authors {

                @XmlElement(name = "Person", required = true)
                protected List<ISBNdb.BookList.BookData.Authors.Person> person;

                /**
                 * Gets the value of the person property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the person property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPerson().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ISBNdb.BookList.BookData.Authors.Person }
                 * 
                 * 
                 */
                public List<ISBNdb.BookList.BookData.Authors.Person> getPerson() {
                    if (person == null) {
                        person = new ArrayList<ISBNdb.BookList.BookData.Authors.Person>();
                    }
                    return this.person;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="person_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Person {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "person_id", required = true)
                    protected String personId;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the personId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPersonId() {
                        return personId;
                    }

                    /**
                     * Sets the value of the personId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPersonId(String value) {
                        this.personId = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="change_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *       &lt;attribute name="price_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *       &lt;attribute name="edition_info" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="language" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="physical_description_text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="lcc_number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="dewey_decimal_normalized" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="dewey_decimal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Details {

                @XmlAttribute(name = "change_time", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar changeTime;
                @XmlAttribute(name = "price_time", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar priceTime;
                @XmlAttribute(name = "edition_info", required = true)
                protected String editionInfo;
                @XmlAttribute(required = true)
                protected String language;
                @XmlAttribute(name = "physical_description_text", required = true)
                protected String physicalDescriptionText;
                @XmlAttribute(name = "lcc_number", required = true)
                protected String lccNumber;
                @XmlAttribute(name = "dewey_decimal_normalized", required = true)
                protected String deweyDecimalNormalized;
                @XmlAttribute(name = "dewey_decimal", required = true)
                protected String deweyDecimal;

                /**
                 * Gets the value of the changeTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getChangeTime() {
                    return changeTime;
                }

                /**
                 * Sets the value of the changeTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setChangeTime(XMLGregorianCalendar value) {
                    this.changeTime = value;
                }

                /**
                 * Gets the value of the priceTime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getPriceTime() {
                    return priceTime;
                }

                /**
                 * Sets the value of the priceTime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setPriceTime(XMLGregorianCalendar value) {
                    this.priceTime = value;
                }

                /**
                 * Gets the value of the editionInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEditionInfo() {
                    return editionInfo;
                }

                /**
                 * Sets the value of the editionInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEditionInfo(String value) {
                    this.editionInfo = value;
                }

                /**
                 * Gets the value of the language property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLanguage() {
                    return language;
                }

                /**
                 * Sets the value of the language property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLanguage(String value) {
                    this.language = value;
                }

                /**
                 * Gets the value of the physicalDescriptionText property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPhysicalDescriptionText() {
                    return physicalDescriptionText;
                }

                /**
                 * Sets the value of the physicalDescriptionText property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPhysicalDescriptionText(String value) {
                    this.physicalDescriptionText = value;
                }

                /**
                 * Gets the value of the lccNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLccNumber() {
                    return lccNumber;
                }

                /**
                 * Sets the value of the lccNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLccNumber(String value) {
                    this.lccNumber = value;
                }

                /**
                 * Gets the value of the deweyDecimalNormalized property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeweyDecimalNormalized() {
                    return deweyDecimalNormalized;
                }

                /**
                 * Sets the value of the deweyDecimalNormalized property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeweyDecimalNormalized(String value) {
                    this.deweyDecimalNormalized = value;
                }

                /**
                 * Gets the value of the deweyDecimal property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeweyDecimal() {
                    return deweyDecimal;
                }

                /**
                 * Sets the value of the deweyDecimal property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeweyDecimal(String value) {
                    this.deweyDecimal = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="publisher_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class PublisherText {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "publisher_id", required = true)
                protected String publisherId;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the publisherId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPublisherId() {
                    return publisherId;
                }

                /**
                 * Sets the value of the publisherId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPublisherId(String value) {
                    this.publisherId = value;
                }

            }

        }

    }

}
