//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.06 at 08:32:50 PM BST 
//


package EngineIsbnDb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the isbndbXml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: isbndbXml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ISBNdb }
     * 
     */
    public ISBNdb createISBNdb() {
        return new ISBNdb();
    }

    /**
     * Create an instance of {@link ISBNdb.BookList.BookData.Authors.Person }
     * 
     */
    public ISBNdb.BookList.BookData.Authors.Person createISBNdbBookListBookDataAuthorsPerson() {
        return new ISBNdb.BookList.BookData.Authors.Person();
    }

    /**
     * Create an instance of {@link ISBNdb.BookList.BookData.Details }
     * 
     */
    public ISBNdb.BookList.BookData.Details createISBNdbBookListBookDataDetails() {
        return new ISBNdb.BookList.BookData.Details();
    }

    /**
     * Create an instance of {@link ISBNdb.BookList }
     * 
     */
    public ISBNdb.BookList createISBNdbBookList() {
        return new ISBNdb.BookList();
    }

    /**
     * Create an instance of {@link ISBNdb.BookList.BookData.PublisherText }
     * 
     */
    public ISBNdb.BookList.BookData.PublisherText createISBNdbBookListBookDataPublisherText() {
        return new ISBNdb.BookList.BookData.PublisherText();
    }

    /**
     * Create an instance of {@link ISBNdb.BookList.BookData.Authors }
     * 
     */
    public ISBNdb.BookList.BookData.Authors createISBNdbBookListBookDataAuthors() {
        return new ISBNdb.BookList.BookData.Authors();
    }

    /**
     * Create an instance of {@link ISBNdb.BookList.BookData }
     * 
     */
    public ISBNdb.BookList.BookData createISBNdbBookListBookData() {
        return new ISBNdb.BookList.BookData();
    }

}
