//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.19 at 07:10:59 PM BST 
//


package EngineIsbnDb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the isbndbPublisherXml.jaxb package. 
 * <p>An ObjectFactoryPublishers allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryPublishers {


    /**
     * Create a new ObjectFactoryPublishers that can be used to create new instances of schema derived classes for package: isbndbPublisherXml.jaxb
     * 
     */
    public ObjectFactoryPublishers() {
    }

    /**
     * Create an instance of {@link ISBNdbPublishers.PublisherList }
     * 
     */
    public ISBNdbPublishers.PublisherList createISBNdbPublisherList() {
        return new ISBNdbPublishers.PublisherList();
    }

    /**
     * Create an instance of {@link ISBNdbPublishers.PublisherList.PublisherData }
     * 
     */
    public ISBNdbPublishers.PublisherList.PublisherData createISBNdbPublisherListPublisherData() {
        return new ISBNdbPublishers.PublisherList.PublisherData();
    }

    /**
     * Create an instance of {@link ISBNdbPublishers.PublisherList.PublisherData.Categories.Category }
     * 
     */
    public ISBNdbPublishers.PublisherList.PublisherData.Categories.Category createISBNdbPublisherListPublisherDataCategoriesCategory() {
        return new ISBNdbPublishers.PublisherList.PublisherData.Categories.Category();
    }

    /**
     * Create an instance of {@link ISBNdbPublishers.PublisherList.PublisherData.Categories }
     * 
     */
    public ISBNdbPublishers.PublisherList.PublisherData.Categories createISBNdbPublisherListPublisherDataCategories() {
        return new ISBNdbPublishers.PublisherList.PublisherData.Categories();
    }

    /**
     * Create an instance of {@link ISBNdbPublishers }
     * 
     */
    public ISBNdbPublishers createISBNdb() {
        return new ISBNdbPublishers();
    }

}
